<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Snowplow\\RefererParser' => array($vendorDir . '/snowplow/referer-parser/php/src'),
    'PhpSpec' => array($vendorDir . '/phpspec/phpspec/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
    'Bllim\\Datatables' => array($vendorDir . '/pragmarx/datatables/src'),
);
